---
title: "mod4_peer_review_zach_young"
output:
  html_document:
    df_print: paged
---

```{r}
# Setup
library(tidyverse)
library(ggplot2)
library(lubridate)

df <- read.csv("C:\\Users\\zacha\\Hyperborea\\r\\csv\\customer.csv")
```

```{r}
# 1) Variable Conversions 
df$Date <- as.Date(df$Date, format = "%m/%d/%Y")
df$Department <- as.factor(df$Department)
df$Category <- as.factor(df$Category)
df$CustomerCode <- as.factor(df$CustomerCode)
str(df)
```

```{r}
# 2) Quantity/Price Summaries 
summary(df$Quantity)
summary(df$Price)
```

```{r}
# 3) Display Null Values
summary(df)
```

```{r}
# 4) Category Bar Chart 
bc <- ggplot(df) +
  geom_bar(aes(x = Category), fill = '#003366')

bc <- bc + labs(title = "Store Inventory",
                x = "Category",
                y = "Quantity")
print(bc)
```

```{r}
# 5) Revenue by Department
df <- df %>%
  mutate(df, Revenue = Price + Quantity)
df <- subset(df, select = -Revenue)
df <- df %>%
  mutate(df, Revenue = Price * Quantity)

ggplot(data = df, aes(x = Department, y = Revenue)) +
  geom_bar(stat = "identity", fill = '#801818')

options(scipen=999)

df %>%
  drop_na(Price, Quantity) %>%
  group_by(Department) %>%
  summarise(Total = sum(Revenue))
```

```{r}
# 6) Histogram and Boxplot 
hist(df$Price)
hist(df$Quantity)

boxplot(df$Price)
boxplot(df$Quantity)
```

```{r}
# 7) Short Essay

#In terms of this respective analysis,R is the most efficient from a less collective standpoint. The strength of Alteryx resides within its workflow capabilities, resulting in a comparatively less difficult replication process when collaborating with a team. However, Power BI trumps both R and Alteryx with its top notch data visualization tools, much at the chagrin of Alteryx's encumbering user interface and licensing costs. Despite requiring more coding experience, R and its open-source environment provides the platform with a robust advantage over its competitors, not to mention its an economically sound option; it's free!
```